import pygame

from app import App
import utils
from utils import COLORS

class App_Engine(App):
	def __init__(self):
		super(App_Engine, self).__init__()
		self.Buttons, self.Texts = utils.load(self, 'App_Engine.json')

	def FirstDraw(self, screen):
		#Draw the background
		self.DrawBackground(screen)

		super(App_Engine, self).FirstDraw(screen)

	def engineToggle(self, btnID):
		#Autogenerated Method Stub
		print('engineToggle - {}'.format(btnID))

