from app import App
import utils
from utils import COLORS

class App_Keyboard(App):
	def __init__(self):
		super(App_Keyboard, self).__init__()
		self.Buttons, self.Texts = utils.load(self, 'App_Keyboard.json')

	def FirstDraw(self, screen):
		#Draw the background
		self.DrawBackground(screen, (0, 255, 255))

		super(App_Keyboard, self).FirstDraw(screen)

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def key_press(self, btnID):
		#Autogenerated Method Stub
		print('key_press - {}'.format(btnID))

	def cancel(self, btnID):
		#Autogenerated Method Stub
		print('cancel - {}'.format(btnID))

	def cancel(self, btnID):
		#Autogenerated Method Stub
		print('cancel - {}'.format(btnID))

