from app import App
import utils
from utils import COLORS

class Panel_Music(App):
	def __init__(self):
		super(Panel_Music, self).__init__()
		self.Buttons, self.Texts = utils.load(self, 'Panel_Music.json')

	def FirstDraw(self, screen):
		#Draw the background
		self.DrawBackground(screen, (160, 160, 160))

		super(Panel_Music, self).FirstDraw(screen)

	def musicPrevious(self, btnID):
		#Autogenerated Method Stub
		print('musicPrevious - {}'.format(btnID))

	def musicShuffle(self, btnID):
		#Autogenerated Method Stub
		print('musicShuffle - {}'.format(btnID))

	def musicFileSelect(self, btnID):
		#Autogenerated Method Stub
		print('musicFileSelect - {}'.format(btnID))

